version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use Dockerfile.dev for development
    ports:
      - "3000:3000"  # Expose port 3000
    volumes:
      - .:/app  # Mount the local directory into the container
      - /app/node_modules  # Avoid synchronizing node_modules
    environment:
      - NODE_ENV=development
